# Usage: python evaluate_addivortes_subsets.py
#
# For every subset generated by generate_earthquake_subsets.py
# (subsets/<n>/<repeat>/train.csv, test.csv), fits an AddiVortesRegressor
# with default parameters, predicting "mag" from all other columns.
# Records in-sample RMSE, out-of-sample RMSE, fit time, and prediction time
# for each repeat, then reports the MEDIAN of each metric across the repeats
# for every value of n.
#
# One batch = all repeats for a single value of n, run together on one
# worker process. Work per batch is roughly proportional to n * repeats
# (~5k-10k total rows), so batches are roughly balanced across workers.
#
# Output: addivortes_results.csv with one row per n, columns:
#   n, repeats, median_in_sample_rmse, median_out_sample_rmse,
#   median_fit_time_s, median_predict_time_s

import csv
import os
import time
import multiprocessing as mp
from pathlib import Path

# Belt-and-braces: also set these before numpy is imported, in case the
# platform's multiprocessing start method is "spawn" (Windows/macOS default),
# where each worker re-imports numpy fresh and these env vars are honored at
# BLAS init time. On "fork" (Linux default) numpy is already imported in the
# parent before workers exist, so this alone isn't sufficient there —
# threadpoolctl below (used in _init_worker) covers that case.
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")

import numpy as np
import pandas as pd

from addivortes import AddiVortesRegressor

SUBSETS_ROOT_DEFAULT = Path(__file__).parent / "subsets"
TARGET_COL = "mag"

FIELDNAMES = [
    "n", "repeats",
    "median_in_sample_rmse", "median_out_sample_rmse",
    "median_fit_time_s", "median_predict_time_s",
]


def _init_worker():
    """Runs once per worker process when the pool starts.

    Pins each worker's BLAS/OpenMP libraries to a single thread. Without
    this, if numpy is linked against a threaded BLAS (OpenBLAS/MKL), every
    one of the worker *processes* could also spawn multiple internal BLAS
    *threads*, oversubscribing the machine's cores. threadpoolctl sets this
    at runtime regardless of whether the worker process was created via
    fork or spawn, unlike the env vars above which only reliably help under
    spawn.
    """
    try:
        from threadpoolctl import threadpool_limits
        threadpool_limits(1)
    except ImportError:
        # threadpoolctl isn't installed; the env vars set at module import
        # time still help under "spawn" start method, so this is a
        # best-effort fallback rather than a hard failure.
        pass


def rmse(y_true, y_pred):
    return float(np.sqrt(np.mean((np.asarray(y_true) - np.asarray(y_pred)) ** 2)))


def run_one(train_path: Path, test_path: Path):
    train_df = pd.read_csv(train_path)
    test_df = pd.read_csv(test_path)

    X_train = train_df.drop(columns=[TARGET_COL])
    y_train = train_df[TARGET_COL]
    X_test = test_df.drop(columns=[TARGET_COL])
    y_test = test_df[TARGET_COL]

    model = AddiVortesRegressor()

    fit_start = time.perf_counter()
    model.fit(X_train, y_train)
    fit_time = time.perf_counter() - fit_start

    predict_start = time.perf_counter()
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    predict_time = time.perf_counter() - predict_start

    in_sample_rmse = rmse(y_train, train_pred)
    out_sample_rmse = rmse(y_test, test_pred)

    return in_sample_rmse, out_sample_rmse, fit_time, predict_time


def process_batch(size_dir_str: str) -> dict:
    """Runs one batch (all repeats for a single n) in a worker process.
    Returns a result row instead of writing to disk directly, so the parent
    process can serialize all writes and avoid concurrent-write corruption."""
    size_dir = Path(size_dir_str)
    n = int(size_dir.name)
    repeat_dirs = sorted(
        (p for p in size_dir.iterdir() if p.is_dir()),
        key=lambda p: int(p.name),
    )

    in_rmses, out_rmses, fit_times, predict_times = [], [], [], []
    for repeat_dir in repeat_dirs:
        in_rmse, out_rmse, fit_time, predict_time = run_one(
            repeat_dir / "train.csv", repeat_dir / "test.csv"
        )
        in_rmses.append(in_rmse)
        out_rmses.append(out_rmse)
        fit_times.append(fit_time)
        predict_times.append(predict_time)

    return {
        "n": n,
        "repeats": len(repeat_dirs),
        "median_in_sample_rmse": float(np.median(in_rmses)),
        "median_out_sample_rmse": float(np.median(out_rmses)),
        "median_fit_time_s": float(np.median(fit_times)),
        "median_predict_time_s": float(np.median(predict_times)),
    }


def _process_batch_safe(size_dir_str: str):
    """Wraps process_batch so a failure in one batch (e.g. a numerical issue
    in the MCMC) is captured and returned rather than propagated as a raw
    exception, which is awkward to handle cleanly through
    Pool.imap_unordered. Returns (n, row_or_None, error_or_None)."""
    n = int(Path(size_dir_str).name)
    try:
        return n, process_batch(size_dir_str), None
    except Exception as exc:
        return n, None, repr(exc)


def load_completed_ns(output_path: Path) -> set:
    """Reads whatever rows already exist in the output log (from a previous,
    possibly interrupted run) so we can skip redoing them."""
    completed = set()
    if not output_path.exists() or output_path.stat().st_size == 0:
        return completed
    with output_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                completed.add(int(row["n"]))
            except (KeyError, ValueError):
                # Malformed/partial trailing row (e.g. from a crash mid-write);
                # skip it rather than fail the whole run.
                continue
    return completed


def default_n_workers() -> int:
    """Picks a worker count appropriate to how the job was launched.
    Respects SLURM's allocation if present, otherwise falls back to all
    visible cores, so the same script works both under sbatch/srun and when
    run manually."""
    for var in ("SLURM_CPUS_PER_TASK", "SLURM_NTASKS", "SLURM_CPUS_ON_NODE"):
        val = os.environ.get(var)
        if val:
            try:
                return int(val)
            except ValueError:
                pass
    try:
        return len(os.sched_getaffinity(0))
    except AttributeError:
        return os.cpu_count() or 1


def evaluate_subsets(
    subsets_root: Path = SUBSETS_ROOT_DEFAULT,
    n_workers: int | None = None,
    resume: bool = True,
):
    here = Path(__file__).parent
    subsets_root = Path(subsets_root)
    output_path = here / "addivortes_results.csv"

    if n_workers is None:
        n_workers = default_n_workers()

    all_size_dirs = sorted(
        (p for p in subsets_root.iterdir() if p.is_dir()),
        key=lambda p: int(p.name),
    )

    completed_ns = load_completed_ns(output_path) if resume else set()
    size_dirs = [d for d in all_size_dirs if int(d.name) not in completed_ns]

    n_skipped = len(all_size_dirs) - len(size_dirs)
    if n_skipped:
        print(f"Resuming: skipping {n_skipped} already-completed batches found in {output_path.name}")

    if not size_dirs:
        print("Nothing to do: all batches already completed.")
        return

    # Only write the header if the file is new/empty; in resume mode we're
    # appending to an existing log, so must never truncate it.
    write_header = not output_path.exists() or output_path.stat().st_size == 0
    if write_header:
        with output_path.open("w", newline="", encoding="utf-8") as f:
            csv.DictWriter(f, fieldnames=FIELDNAMES).writeheader()

    # One worker process per batch, capped at n_workers (available CPU
    # threads). With more batches than workers, the pool queues the
    # remainder and picks them up as workers free.
    n_workers = min(n_workers, len(size_dirs)) or 1
    print(f"Running {len(size_dirs)} batches across {n_workers} worker processes...")

    # chunksize=1: each worker pulls one batch at a time from the queue.
    # Batches have varying cost (n varies from 100 to 10000), so a larger
    # chunksize could let one worker get stuck with several slow batches
    # while others sit idle; chunksize=1 keeps the pool balanced.
    with mp.Pool(processes=n_workers, initializer=_init_worker) as pool:
        results_iter = pool.imap_unordered(
            _process_batch_safe,
            [str(d) for d in size_dirs],
            chunksize=1,
        )

        # Always append here: header (if any) was already written above, and
        # in resume mode the file may already contain prior rows.
        with output_path.open("a", newline="", encoding="utf-8") as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=FIELDNAMES)
            for i, (n, row, error) in enumerate(results_iter, 1):
                if error is not None:
                    print(f"[FAILED] n={n} -> {error}")
                    continue
                writer.writerow(row)
                csv_file.flush()  # persist incrementally in case of crash/preemption
                print(f"[{i}/{len(size_dirs)}] done: {row}")


if __name__ == "__main__":
    evaluate_subsets()
